services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    region: oregon
    plan: free
    pythonVersion: 3.10
